<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Frequent Flyer                       1dria AirwaysAegean AirlinesAereonautica militareAero 2000 SAAero ContractorsAer</name>
   <tag></tag>
   <elementGuidId>870653b4-0f9b-4102-a1c0-d6adda94d82e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='frq_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frq_0_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>airlineSelectedAdult[rowIndex].paxFrequentFlyer[$index].airlineCode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>freqFlyrFunc('frq_'+rowIndex+'_'+$index)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																Select Frequent Flyer                       12 North1Time Airline40-Mile Air testingAbacus InternationalABSA - Aerolinhas BrasileirasAdria AirwaysAegean AirlinesAereonautica militareAero 2000 SAAero ContractorsAero LankaAero MongoliaAeroflotAeroflot-DonAeroline GmbHAerolitoralAeropelican Air ServicesAeroRepAFRIQIYAH AIRWAYSagainmuktaAigle AzurAir AfriqueAir AlgerieAir Alps Aviation (A6)Air ArabiaAir Arabia EgyptAir Arabia MarocAir ArmeniaAir BaganAir BangladeshAir BourbonAir BurkinaAir BusanAir CalAir CanadaAir Canada JazzAir Cargo GermanyAir CentralAir ChathamsAIR CHINA INTERNATIONALAir Choice OneAir Comet ChileAir FoyleAir FranceAir GeorgianAir GreenlandAir GuyaneAir IcelandAir IndiaAir India ExpressAir India RegionalAir IndusAir ItalyAir JamaicaAir JapanAir KazakhstanAir KiribatiAir KoryoAir LibertAir MacauAir MandalayAir Marshall IslandsAir MediterraneeAir NipponAir NiuginiAir North Charter - CanadaAir NostrumAir PacificAir PhilippinesAir RarotongaAir Saint PierreAir SeychellesAir SinaiAir TahitiAir TindiAir TransatAir UgandaAir UrgaAir VolgaAir WisconsinAir ZimbabweAir2thereAirAsiaAirAsia XAirblueAiresAirlinairAirlines Of TasmaniaAirlines PNGAirlink (SAA)AirnorthAirRussiaAl-Naser AirlinesALAKAlaska AirlinesAlaska Seaplane ServiceAlidauniaAlitaliaAlitalia CitylinerAll Nippon AirwaysAllegiant AirAlliance AirlinesAlMasria Universal AirlinesAloha AirlinesAlrosaAmaszonasAmerica West AirlinesAmerican AirlinesAmerican Eagle AirlinesANA WingsAOM French AirlinesArgentinasAriana Afghan AirlinesArik AirArkia Israeli AirlinesAserca AirlinesAsian SpiritAsian Wings AirwaysAsiana AirlinesAstairAstanaAthens AirwaysAtiflyAtlantic Airways Faroe IslandsAtlantic Southeast AirlinesAtlantis European AirwaysAtlas BlueAtlasjetAUOSAurigny Air ServicesAuroraAustral AirAustral BrasilAustral Lineas AereasAustrianAustrian ArrowsAviabusAvialeasing Aviation CompanyAviancaAvianova (Russia)AviesAvirexAws expressAzerbaijanAzul LinhasBA CityFlyerBahamasairBalkan Bulgarian AirlinesBaltic AirBaltic Air linesBangkok AirwaysBarents AirLinkBearskin Lake Air ServiceBelair AirlinesBelaviaBering AirBerlin AirBiman Bangladesh AirlinesBinter CanariasBishkekBlack Stallion AirwaysBlue AirBlue PanoramaBlue1Bmi British Midlandbmi RegionalBNewbnvcncBotswana AirBraathensBRAZIL AIRBrit AirBritish AirwaysBritish Mediterranean AirwaysBrussels AirlinesBuffalo AirwaysBulgaria AirBuquebus Líneas AéreasBusiness AviationBusinessAirBVI AirwaysCaledonieCalima AviacionCalm AirCamair-coCambodia Angkor Air (K6)Canadian AirlinesCanadian National AirwaysCanadian NorthCanXplorerCanXpressCape AirCaraibesCargo Plus AviationCaribbeanCaribbean Star AirlinesCarnival Air LinesCaspian AirlinesCathay PacificCatovairCaucasus AirlinesCayman AirwaysCB Airways UK ( Interliging Flights )CCML AirlinesCebu PacificCHINA AIRLINESChina EasternChina Northern AirlinesChina Northwest AirlinesChina Northwest Airlines (WH)China Southern AirlinesChina SSSChina UnitedChina United AirlinesChongqing AirlinesCiao AirCimber AirCityJetClick (Mexicana)Coastal AirComairCommutAirCompagnie Aerienne Du MaliCompass AirlinesCondor FlugdienstCongo ExpressContact AirContinental AirlinesContinental ExpressContinental MicronesiaConviasaCopaCorsairCorse-MediterraneeCroatia AirlinesCubanaCyprus Turkish AirlinesCzech AirlinesDaallo AirlinesDana AirDanube Wings (V5)Darwin AirlineDAT Danish Air TransportdbaDeltaDennis SkyDeutsche BahnDK TESTDnieproaviaDolomitiDomenican AirlinesDonbassAeroDragonairDruk AirEagle AirEastar JetEastern AirwaysEastland AireasyJetEasyJet (DS)Edelweiss AirEgyptaireimatestEL AL ISRAEL AIRLINESEl-Buraq Air TransportEmiratesEmpire AirlinesEpic HolidayEra AlaskaEritrean AirlinesEthiopianEtihadEuro Exec ExpressEurofly ServiceEurolineEuropa AirEuropeSkyEurowingsEva AirwaysExpo AviationExpressJetFar Eastern Air TransportFelix AirwaysFinnairFinncomm AirlinesFireflyFirst AirFive Fourty AviationFly 6ixFly BrasilFly Colombia ( Interliging Flights )Flybaboo Sa GeneveFLYBEFLYDUBAIFlyglobespanFlyLalFLYNASFlyNordicFrontier AirlinesFrontier Flying ServiceFuji Dream AirlinesGambia BirdGaruda IndonesiaGazpromGB AirwaysGeorgian AirwaysGeorgian National AirlinesGerman International Air LinesGermaniaGermanwingsGlobusGNB Linhas AereasGo AirGoJet AirlinesGol Linhas Aéreas InteligentesGomelaviaGreat Lakes AirlinesGreenflyGryphon AirlinesGulf AirHageland Aviation ServicesHahn AirHahn Air SystemsHainan AirlinesHaiti Ambassador AirlinesHalcyonairHankook AirlineHapagflyHarbour Air (Priv)Hawaiian AirlinesHawkairHeli Air MonacoHeli FranceHelijetHellas JetHelvetic AirwaysHewa Bora AirwaysHex'AirHi Fly (5K)Himalayan AirlinesHokkaido International AirlinesHong Kong AirlinesHong Kong ExpressHorizon AirHorizon AirlinesHuaxiaIBC AirwaysIberiaIberia ExpressIbex AirlinesIcelandairIndian AirlinesIndiGo AirlinesIndonesia AirAsiaIndya Airline GroupInterair South AfricaInterjet (ABC Aerolineas)Iran AirIran Aseman AirlinesIraqi AirwaysIsland Air (WP)Island AirlinesIsland SpiritIslena De InversionesIsrairItek AirJAL ExpressJapan Air SystemJapan InternationalJapan RegioJapan TransoceanJatJazeera AirwaysJeju AirJet AirwaysJet LiteJetairflyJetAirways oldJetblue AirwaysJetstar AirwaysJetstar Asia AirwaysJetstar PacificJin AirJobAirJordan AviationJoy AirJuneyao AirlinesJusur airwaysKam AirKenmore AirKenya AirwaysKish AirKLMKLM CityhopperKogalymaviaKomiinteraviaKorean AirKostromskie avialiniiKSYKuban AirlinesKuwait AirwaysKyrgyzstanKyrgyzstanKyrgyzstan AirlinesLacsaLam MozambiqueLan AirlinesLAN ExpressLAN PeruLanecuadorLaoLCM AIRLINESLiatLibyan Arab AirlinesLine BlueLingus LimitedLinhas ALion Mentari AirlinesLionXpressLot - PolishLSM AirlinesLSM International Luchsh Airlines Luftfahrtgesellschaft WalterLufthansaLufthansaLufthansa CityLineLufttransportLugansk AirlinesLuxairMadagaskarMaerskMahan AirMalaysiaMaldivianMaldivo AirlinesMalmo AviationMaltaMandarin AirlinesMangoMarusya AirwaysMarysya AirlinesMauritiusMaya Island AirMDLR AirlinesMed AirwaysMeridianaMesa AirlinesMetro BataviaMiat MongolianMichael AirlinesMiddle EastMidwest AirlinesMidwest Airlines (Egypt)MoldovaMonarch AirlinesMongolian AirlinesMontenegro AirlinesMotor SichMount Cook AirlinesMyanma AirwaysMyanmar AirwaysMyway AirlinesN1Namibia AirNas AirNational Jet SystemsNauru Air CorporationNeosNepal AirlinesNew England AirlinesNew Zealand AirNEXT BrasilNikiNile AirNok AirNordaviaNordic RegionalNorte Lineas AereasNorth-Wright AirwaysNorthwest AirlinesNorthwestern AirNorwegian Air InternationalNorwegian Air ShuttleNouvelairOceanairOceanic AirlinesoctaOlympic AirlinesOman AirOneChinaOnur AirOrbit Airlines AzerbaijanOrchid AirlinesOrenairOrient Thai AirlinesOverland AirwaysPacific Coastal AirlinePacific WingsPakistanPal airlinesPalestinian AirlinesPan Am World Airways DominicanaPanAm World AirwaysPapillon Grand Canyon HelicoptersParmiss Airlines (IPV)Patriot AirwaysPeach AviationPegasusPEGASUS AIRLINES-PelitaPeninsula AirwaysPhilippine AirlinesPiedmont AirlinesPinnacle AirlinesPobedaPoletPolynesian AirlinesPorter AirlinesPortugaliaPotomac AirPrecision Air ServicesPrimera AirProflight Commuter ServicesQANTASQatarQatXpressRACSARed Jet AndesRed Jet CanadaRed Jet MexicoRed WingsRégionalRegional AirlinesRegional ExpressReno AirRepublic AirlinesRossiyaRoyal Air CambodgeRoyal Air MarocRoyal BruneiRoyal FalconRoyal JordanianRUSSIARwandair LimitedRyanairS7SafairSafi AirwaysSAM ColombiaSanta BarbaraSaratovskiiSASSata Acores AirSata InternationalSATENASaudi ArabianSCATScootsdcsxdSeaborne AirlinesSenegal AirlinesSENIC AIRLINESSerbian AirlinesSGA AirlinesShaheen Air InternationalShandong AirlinesShanghai AirlinesSharp AirlinesShenzhen AirlinesShuttle (Usair Shuttle)Shuttle AmericaSichuan AirlinesSierra National AirlinesSilk AirSingaporeSingaporeSky AirlineSky ExpressSky RegionalSky Wing PacificSkyjet AirlinesSkymark AirlinesSkynet Asia AirwaysSkyWestSkywest AustraliaSkywork AirlinesSmartLynx AirlinesSmartwingsSOCHI AIRSolomon AirlinesSomon AirSouth AfricanSouth East Asian AirlinesSouthwest AirlinesSpicejetSpirit AirlinesSpring AirlinesSrilankanSriwijaya AirStar FlyerStarbow AirlinesStarline.kzSTP AirwaysStrategic AirlinesSudan AirwaysSun Air of ScandinaviaSun Country AirlinesSun D**OrSun ExpressSunflower AirlinesSunwingSunwing AirlinesSurinam AirwaysSwissSwissairSyphaxSyrian Arab AirlinesTAAG Angola AirlinesTaca InternationalTACA PeruTACV CABO VERDE AIRLINESTahiti Nui AirTaimyrTajikTAMTam Linhas AereasTAMETandem AeroTanzania AirTap Portugal AirTarom - Romanian TransportTassili Airlinestest airlinetesting lccTexas WingsThai AirAsiaThai AirwaysThomas Cook AirlinesThomas Cook AirlinesTiara AirTiger AirwaysTiger Airways AustraliaTrans Mediterranean AirlinesTrans Pas AirTrans States AirlinesTrans World AirlinesTransAsia AirwaysTransavia FranceTransavia HollandTransBrasil AirlinesTransHoldingTransportes AeromarTranswest AirTRIP Linhas ATropic AirTui Nederland AirlinesTUIflyTUIfly (X3)TUIfly NordicTuninterTunis AirTurkish AirlinesTurkmenhowayollaryTway AirlinesTwin JetU.S. AirUIAUM AirlinesUni AirwaysUnited AirlinesUnited AirwaysUralUS AirwaysUS Helicopter CorporationUsa Sky CargoUtairUtair-ExpressUzbekistanVanuatuVaustraliaViaggio AirVickJetVietnamVIM AirlinesVIP EcuadorVirgin AmericaVirgin AtlanticVirgin AustraliaVirgin ExpressVirgin Nigeria AirwaysVirgin PacificVirginwingsVistara VLM AirlinesVolarisVRG Linhas AereasVueling AirlinesVueling AirlinesVVYWayraperWebJet Linhas AWest Air ChinaWest Coast AirWestern AirlinesWestjet AirlinesWiderøeWindward IslandsWings AirWings of AlaskaWizz AirWorld Experience AirlineXiamen IamenXpressairYakutiaYamalYamal AirlinesYangon AirwaysYangtze River ExpressYellowstone Club Private ShuttleYemenia YemenYeti AirwaysYunnan AirlinesZabaykalskii AirlinesZagrosjetZambezi Airlines (ZMA)Zambia SkywaysZenith International AirlineZest AirZipZz 
															</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frq_0_0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='frq_0_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='passengerDetail']/div/div[2]/div/div/div[5]/section/div[2]/div[2]/div[2]/div[2]/div[4]/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airline:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
